### ISSUE TITLE
clean up + audit of `bcd_backtrace_*` code 

### ISSUE THREAD

**Issue by abelmathew** [backtrace-labs/bcd#9]
As discussed with @dkopko, filing an issue for follow up discussion.

**Comment by dkopko** [comment]
Code like this is sloppy, used incorrectly, and needs to go:
```
907)       union {
908)               char *argv[BCD_ARGC_LIMIT];
909)               const char *cargv[BCD_ARGC_LIMIT];
910)       } u;
```
We should not have an array with mixed memory constness, accessed alternativelty by one of the two backdoors that the union gives.  There is no sensible way to reliably free this memory later as there will be mixed const and non-const (allocated) elements.   The entire array should be non-const, and any const sources of for elements should be strdup()ed and their copy put in the array.

**Comment by dkopko** [comment]
Code like this looks incorrect to me:
```
628) fail:
629)       while (i-- > 0)
630)               free(output[i]);
```
The value of i needs to be pre-decremented and the comparison needs to be >= 0 in order for this code to be correct.

**Comment by dkopko** [comment]
bcd_kv_set() should probably use TAILQ_INSERT_TAIL() for consistency with dho's additions, and in order to not invert a given order of kvs unnecessarily.

**Comment by dkopko** [comment]
Checks like this are redundant and also wrong:
```
474)       if (n_output > bcd_kv_count)
475)               limit = bcd_kv_count;
476) 
477)       if (limit > BCD_ARGC_LIMIT)
478)               limit = BCD_ARGC_LIMIT;
```
bcd_kv_count is implicit in the length of the list bcd_kv_list.  BCD_ARGC_LIMIT is irrelevant here because it is already the boundary we are using prior to this call to derive the argument n_output.  BCD_ARGC_LIMIT is wrong here because output argument is already an offset within an array of length BCD_ARGC_LIMIT, and so our actual limit need actually be *shorter* than BCD_ARGC_LIMIT.

**Comment by dkopko** [comment]
This code in `bcd_execve()` seems wrong, as per @abelmathew :
```
848)       while (argv[fr] != NULL)
849)               free(argv[fr++]);
```
argv has become a mix of const and non-const char*'s and so we can't just assume some non-const suffix needs to be free()d.  Better to just turn argv into only non-const pointers and just free all of them, and get rid of the cryptic `fr` argument.
